db:
  host: 127.0.0.1
  username: tongct425
  pwd: testpwd123
# 日志配置
log:
  disable-caller: false
  disable-stacktrace: false
  level: debug
  format: console
  output-paths: [tmp/tkblog.log, stdout]

# gin 相关配置
runmode: debug
# 这里的端口号有个冒号?
addr: :8080
