// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: tkblog/v1/tkblog.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TkBlog_ListUser_FullMethodName = "/v1.TkBlog/ListUser"
)

// TkBlogClient is the client API for TkBlog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TkBlogClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type tkBlogClient struct {
	cc grpc.ClientConnInterface
}

func NewTkBlogClient(cc grpc.ClientConnInterface) TkBlogClient {
	return &tkBlogClient{cc}
}

func (c *tkBlogClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, TkBlog_ListUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TkBlogServer is the server API for TkBlog service.
// All implementations must embed UnimplementedTkBlogServer
// for forward compatibility
type TkBlogServer interface {
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedTkBlogServer()
}

// UnimplementedTkBlogServer must be embedded to have forward compatible implementations.
type UnimplementedTkBlogServer struct {
}

func (UnimplementedTkBlogServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedTkBlogServer) mustEmbedUnimplementedTkBlogServer() {}

// UnsafeTkBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TkBlogServer will
// result in compilation errors.
type UnsafeTkBlogServer interface {
	mustEmbedUnimplementedTkBlogServer()
}

func RegisterTkBlogServer(s grpc.ServiceRegistrar, srv TkBlogServer) {
	s.RegisterService(&TkBlog_ServiceDesc, srv)
}

func _TkBlog_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TkBlogServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TkBlog_ListUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TkBlogServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TkBlog_ServiceDesc is the grpc.ServiceDesc for TkBlog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TkBlog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TkBlog",
	HandlerType: (*TkBlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _TkBlog_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tkblog/v1/tkblog.proto",
}
